[server]
    address = ":9290"

[logger]
    # logger level
    level = "debug"
    # log file max size (MB)
    max-size = 100
    # log file save days
    max-age = 15
    # log file max num
    max-backups = 15
    # log file storage dir
    output = "/home/whales/log"
    # enabled stdout
    stdout = true

[etw]
    # if enabled, etw will trace process event
    [etw.process]
        enabled = false
    
    # if enabled, etw will trace thread event
    [etw.thread]
        enabled = false

    # if enabled, etw will trace imageload event
    [etw.image]
        enabled = false

    # if enabled, etw will trace registry event
    [etw.file]
        enabled = false

    # if enabled, etw will trace registry event
    [etw.registry]
        enabled = false

    # if enabled, etw will trace tcp/ip event
    [etw.network]
        enabled = true
    
    # if enabled, etw will trace diskfileio/fileio/fileioinit event
    [etw.diskio]
        enabled = false

[yara]
    # if enabled, when process start will scan process memory
    enabled = false
    # rule paths
    rules = []